name: cdv
channels:
  - defaults
  - conda-forge
  - ncar
dependencies:
  - anyio=2.1.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - bleach=3.3.0
  - cartopy=0.21.1
  - cffi=1.14.5
  - cmaps=1.0.5
  - colorama=0.4.4
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - geocat-viz=2022.7.0
  - idna=3.1
  - ipykernel=5.4.3
  - ipyleaflet=0.17.3
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - Jinja2=2.11.3
  - jsonschema=3.2.0
  - jupyter_client=6.1.11
  - jupyter_core=4.7.1
  - jupyter_server=1.3.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - MarkupSafe=1.1.1
  - matplotlib=3.7.1
  - mistune=0.8.4
  - nbclient=0.5.2
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.5.1
  - notebook=6.2.0
  - numpy=1.23.3
  - openpyxl=3.0.10
  - packaging=20.9
  - pandas=1.4.3
  - pandocfilters=1.4.3
  - parso=0.8.1
  - pickleshare=0.7.5
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.16
  - pycparser=2.20
  - Pygments=2.8.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - python=3.8.8
  - python-dateutil=2.8.1
  - pyzmq=22.0.3
  - Send2Trash=1.5.0
  - six=1.15.0
  - sniffio=1.2.0
  - testpath=0.4.4
  - tornado=6.1
  - traitlets=5.0.5
  - voila=0.2.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - widgetsnbextension=3.5.1
  - xarray=2022.6.0         
